# Host and Ports for API Server
# Either http or https will start depending on if valid private_key and
# certificate names are specified below. Otherwise app is started with http
# WARNING: You should obtain a valid certificate immediately to avoid loss
# of data confidentiality.
# Additionally, key and certificate downloads via the API key will be disabled
# if the server is running as http.
hostname: "localhost"
https_port: 4055
http_port: 4050

# Server logging level (valid levels are: debug, info, warn, error, dpanic,
# panic, and fatal)
log_level: "info"

# Should the server also host the frontend?
serve_frontend: true

# API Server's key and cert
# These names should match the 'name' field of the desired key and cert within
# the application.
# If not specified (or invalid), a self-signed cert is created on each launch
# until proper values are specified.
private_key_name: legocerthub
certificate_name: legocerthub

# Development mode
# This should NEVER be true in production
# Disables key SECURITY features!
dev_mode: false

# Challenge Providers
challenge_providers:
  # http-01 internal server
  http_01_internal:
    enable: true
    # port to run the http challenge server on
    port: 4060
  dns_01_cloudflare:
    enable: false
    account_email: user@example.com
    account_api_key: 12345abcde
